# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: engined/rpc/system.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
  name='engined/rpc/system.proto',
  package='sigmavault.system',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=_b('\n\x1a\x65ngineed/rpc/system.proto\x12\x10sigmavault.system\"@\n\nMemoryUsage\x12\x0c\n\x04used\x18\x01 \x01(\x04\x12\r\n\x05total\x18\x02 \x01(\x04\x12\x15\n\rused_percent\x18\x03 \x01(\x01\"`\n\x16GetSystemStatusRequest\x12\x11\n\t_hostname\x18\x01 \x01(\t\x12\x0e\n\x06uptime\x18\x02 \x01(\x04\x12\x11\n\tcpu_usage\x18\x03 \x01(\x01\x12\x30\n\x0cmemory_usage\x18\x04 \x01(\x0b\x32\x1a.sigmavault.system.MemoryUsage\x12\x15\n\rload_average\x18\x05 \x03(\x01\" \n\x17GetSystemStatusResponse2\x85\x01\n\rSystemService\x12t\n\x0fGetSystemStatus\x12%.sigmavault.system.GetSystemStatusRequest\x1a&.sigmavault.system.GetSystemStatusResponse\"\x00\x62\x06proto3')
)

_MEMORYUSAGE = _descriptor.Descriptor(
  name='MemoryUsage',
  full_name='sigmavault.system.MemoryUsage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='used', full_name='sigmavault.system.MemoryUsage.used', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total', full_name='sigmavault.system.MemoryUsage.total', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='used_percent', full_name='sigmavault.system.MemoryUsage.used_percent', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=104,
)

_GETSYSTEMSTATUSREQUEST = _descriptor.Descriptor(
  name='GetSystemStatusRequest',
  full_name='sigmavault.system.GetSystemStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=112,
)

_GETSYSTEMSTATUSRESPONSE = _descriptor.Descriptor(
  name='GetSystemStatusResponse',
  full_name='sigmavault.system.GetSystemStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostname', full_name='sigmavault.system.GetSystemStatusResponse.hostname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uptime', full_name='sigmavault.system.GetSystemStatusResponse.uptime', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cpu_usage', full_name='sigmavault.system.GetSystemStatusResponse.cpu_usage', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='memory_usage', full_name='sigmavault.system.GetSystemStatusResponse.memory_usage', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='load_average', full_name='sigmavault.system.GetSystemStatusResponse.load_average', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=202,
)

_SYSDB = _symbol_database.Default()
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MemoryUsage = _reflection.GeneratedProtocolMessageType('MemoryUsage', (_message.Message,), {
  'DESCRIPTOR' : _MEMORYUSAGE,
  '__module__' : 'engined.rpc.system_pb2'
  # @@protoc_insertion_point(class_scope:sigmavault.system.MemoryUsage)
  })
_sym_db.RegisterMessage(MemoryUsage)

GetSystemStatusRequest = _reflection.GeneratedProtocolMessageType('GetSystemStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSYSTEMSTATUSREQUEST,
  '__module__' : 'engined.rpc.system_pb2'
  # @@protoc_insertion_point(class_scope:sigmavault.system.GetSystemStatusRequest)
  })
_sym_db.RegisterMessage(GetSystemStatusRequest)

GetSystemStatusResponse = _reflection.GeneratedProtocolMessageType('GetSystemStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSYSTEMSTATUSRESPONSE,
  '__module__' : 'engined.rpc.system_pb2'
  # @@protoc_insertion_point(class_scope:sigmavault.system.GetSystemStatusResponse)
  })
_sym_db.RegisterMessage(GetSystemStatusResponse)


# @@protoc_insertion_point(module_scope)</content>
<parameter name="filePath">c:\Users\sgbil\sigmavault-nas-os\src\engined\engined\rpc\system_pb2.py