# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# Regenerated for grpcio >= 1.68 compatibility.
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from engined.rpc import system_pb2 as system__pb2


class SystemServiceStub:
    """System service stub (client-side)."""

    def __init__(self, channel):
        self.GetSystemStatus = channel.unary_unary(
            "/sigmavault.system.SystemService/GetSystemStatus",
            request_serializer=system__pb2.GetSystemStatusRequest.SerializeToString,
            response_deserializer=system__pb2.GetSystemStatusResponse.FromString,
        )


class SystemServiceServicer:
    """System service servicer (server-side base class)."""

    def GetSystemStatus(self, request, context):
        """Get current system status."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SystemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetSystemStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetSystemStatus,
            request_deserializer=system__pb2.GetSystemStatusRequest.FromString,
            response_serializer=system__pb2.GetSystemStatusResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "sigmavault.system.SystemService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
