# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from engined.rpc import system_pb2 as system__pb2


class SystemServiceStub(object):
    """System service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSystemStatus = channel.unary_unary(
                '/sigmavault.system.SystemService/GetSystemStatus',
                request_serializer=system__pb2.GetSystemStatusRequest.SerializeToString,
                response_deserializer=system__pb2.GetSystemStatusResponse.FromString,
                )


class SystemServiceServicer(object):
    """System service definition
    """

    def GetSystemStatus(self, request, context):
        """Get current system status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSystemStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStatus,
                    request_deserializer=system__pb2.GetSystemStatusRequest.FromString,
                    response_serializer=system__pb2.GetSystemStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sigmavault.system.SystemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SystemService(object):
    """System service definition
    """

    @staticmethod
    def GetSystemStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sigmavault.system.SystemService/GetSystemStatus',
            system__pb2.GetSystemStatusRequest.SerializeToString,
            system__pb2.GetSystemStatusResponse.FromString,
            options, channel_credentials,
            call_credentials, insecure, compression, wait_for_ready, timeout, metadata)</content>
<parameter name="filePath">c:\Users\sgbil\sigmavault-nas-os\src\engined\engined\rpc\system_pb2_grpc.py